apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-demo
  labels:
    app: nodejs-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-demo
  template:
    metadata:
      labels:
        app: nodejs-demo
    spec:
      containers:
        - name: nodejs-demo
          image: 648056969700.dkr.ecr.us-east-1.amazonaws.com/nodejs-demo-app:1.0.0
          ports:
            - containerPort: 3000
